sudo: false

language: node_js

node_js:
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'

before_install:
  - if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -eq 5 ]; then
      npm i -g npm@4;
    fi

after_success:
  - if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -ge 6 ]; then
      npm run coveralls;
    fi

os:
  - linux
  - osx
